// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Global {
    pub id: u8,
    pub start: u64,
    pub raw_physics: Vec<u8>,
}

impl TableType for Global {
    const TABLE_NAME: &'static str = "Global";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for Global {
    type PrimaryKey = u8;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.id
    }
}

impl Global {
    #[allow(unused)]
    pub fn filter_by_id(id: u8) -> Option<Self> {
        Self::find(|row| row.id == id)
    }
    #[allow(unused)]
    pub fn filter_by_start(start: u64) -> TableIter<Self> {
        Self::filter(|row| row.start == start)
    }
    #[allow(unused)]
    pub fn filter_by_raw_physics(raw_physics: Vec<u8>) -> TableIter<Self> {
        Self::filter(|row| row.raw_physics == raw_physics)
    }
}
