// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct TickPhysicsArgs {}

impl Reducer for TickPhysicsArgs {
    const REDUCER_NAME: &'static str = "_tick_physics";
}

#[allow(unused)]
pub fn tick_physics() {
    TickPhysicsArgs {}.invoke();
}

#[allow(unused)]
pub fn on_tick_physics(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<TickPhysicsArgs> {
    TickPhysicsArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let TickPhysicsArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn once_on_tick_physics(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<TickPhysicsArgs> {
    TickPhysicsArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let TickPhysicsArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn remove_on_tick_physics(id: ReducerCallbackId<TickPhysicsArgs>) {
    TickPhysicsArgs::remove_on_reducer(id);
}
